import { NextResponse } from 'next/server';
import { getScaffoldTemplate } from '@/lib/portfolio/scaffold';
import type { ProjectType } from '@/lib/portfolio/types';

// POST /api/portfolio/scaffold/preview
// Body: { type: ProjectType; answers: Record<string, string> }
// Returns: { files: { name: string; description: string }[] }
export async function POST(req: Request): Promise<NextResponse> {
  try {
    const body = (await req.json()) as {
      type?: string;
      answers?: Record<string, string>;
    };

    const type = (body.type ?? '').trim() as ProjectType;
    const validTypes: ProjectType[] = [
      'code',
      'research',
      'business',
      'creative',
      'custom',
    ];

    if (!validTypes.includes(type)) {
      return NextResponse.json(
        { success: false, error: 'invalid type' },
        { status: 400 },
      );
    }

    const template = getScaffoldTemplate(type);

    // Build preview list with resolved file names and static descriptions.
    // We do NOT execute content functions here — just describe what will be created.
    const files = template.files.map((f) => ({
      name: f.path,
      description: f.description ?? `${f.path} — generated by Greg scaffold`,
    }));

    return NextResponse.json({ success: true, data: { files } });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Internal error';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 },
    );
  }
}
