/**
 * pr-description-builder.ts — PR Description Builder — Phase 7H
 *
 * Generates the GitHub PR body markdown from a manifest and post-processing
 * SHIM scores. Auto-generated — no manual editing required.
 *
 * BLUEPRINT §7.7
 */

export interface PRDescriptionInput {
  manifestId: string;
  goalSummary: string;
  targetComponent: string;
  filesChanged: string[];
  shimScoreBefore: number | null;
  shimScoreAfter: number | null;
  sessionLogLink?: string;
}

/**
 * buildPRDescription — render the markdown body for a self-evolution PR.
 */
export function buildPRDescription(input: PRDescriptionInput): string {
  const {
    manifestId,
    goalSummary,
    targetComponent,
    filesChanged,
    shimScoreBefore,
    shimScoreAfter,
    sessionLogLink,
  } = input;

  const fileList = filesChanged.length > 0
    ? filesChanged.map((f) => `- \`${f}\``).join('\n')
    : '_No files modified._';

  const scoreBefore = shimScoreBefore != null ? shimScoreBefore.toFixed(1) : 'n/a';
  const scoreAfter  = shimScoreAfter  != null ? shimScoreAfter.toFixed(1)  : 'n/a';

  const logSection = sessionLogLink
    ? `View full session log: [Session ${manifestId}](${sessionLogLink})`
    : `Session ID: \`${manifestId}\``;

  return [
    `## ${goalSummary}`,
    '',
    `**Session:** ${manifestId}`,
    `**Type:** Self-Evolution`,
    `**Target:** ${targetComponent}`,
    '',
    '### Changes',
    fileList,
    '',
    '### SHIM Quality',
    '| | Score |',
    '|---|---|',
    `| Before | ${scoreBefore} |`,
    `| After | ${scoreAfter} |`,
    '',
    '### Session Log',
    logSection,
    '',
    '---',
    '*Generated by GregLite Self-Evolution Mode*',
  ].join('\n');
}
