/**
 * Message Component — Sprint 2D update
 *
 * Renders a single message in the strategic thread.
 * Assistant messages: full markdown via react-markdown + remark-gfm.
 * Code blocks: Shiki syntax highlighting + language label + copy + open-in-editor.
 *
 * Design: docs/DESIGN_SYSTEM.md Part 3 (Message Rendering)
 */

'use client';

import { useState, useEffect } from 'react';
import { Copy, Check, ExternalLink } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { Components } from 'react-markdown';
import { nanoid } from 'nanoid';
import { useArtifactStore } from '@/lib/artifacts/store';
import { detectArtifact } from '@/lib/artifacts/detector';
import type { Artifact } from '@/lib/artifacts/types';

// ─── Shiki singleton ─────────────────────────────────────────────────────────
// Initialised once; subsequent calls return the cached promise.

import type { Highlighter } from 'shiki';

let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  if (!highlighterPromise) {
    highlighterPromise = import('shiki').then(({ createHighlighter }) =>
      createHighlighter({
        themes: ['github-dark'],
        langs: [
          'typescript', 'tsx', 'javascript', 'jsx',
          'python', 'rust', 'go', 'java', 'c', 'cpp',
          'sql', 'json', 'yaml', 'toml', 'bash', 'sh',
          'html', 'css', 'markdown', 'text',
        ],
      }),
    );
  }
  return highlighterPromise;
}

// ─── Shiki code block ────────────────────────────────────────────────────────

interface ShikiBlockProps {
  code: string;
  language: string;
}

function ShikiBlock({ code, language }: ShikiBlockProps) {
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    getHighlighter()
      .then((hl) => {
        // Normalise unknown languages to 'text' so Shiki never throws
        const langs = hl.getLoadedLanguages() as string[];
        const lang = langs.includes(language) ? language : 'text';

        const highlighted = hl.codeToHtml(code, {
          lang,
          theme: 'github-dark',
        });

        if (!cancelled) setHtml(highlighted);
      })
      .catch(() => {
        // Fallback: plain rendering
        if (!cancelled) setHtml(null);
      });

    return () => { cancelled = true; };
  }, [code, language]);

  if (!html) {
    // Plain fallback while Shiki loads (or on error)
    return (
      <pre className="overflow-x-auto rounded-b bg-[#0d1117] p-4 text-xs font-mono text-[var(--ice-white)]">
        <code>{code}</code>
      </pre>
    );
  }

  return (
    <div
      className="overflow-x-auto rounded-b text-xs [&>pre]:!bg-[#0d1117] [&>pre]:p-4 [&>pre]:m-0"
      // Safe: HTML is generated by Shiki from our own code string, never from user input
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

// ─── Inline code block with toolbar ──────────────────────────────────────────

interface CodeBlockProps {
  code: string;
  language: string;
  inline?: boolean;
}

function CodeBlock({ code, language, inline = false }: CodeBlockProps) {
  const [copied, setCopied] = useState(false);
  const { setArtifact } = useArtifactStore();

  if (inline) {
    return (
      <code className="rounded bg-[var(--elevated)] px-1.5 py-0.5 font-mono text-xs text-[var(--cyan)]">
        {code}
      </code>
    );
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch { /* clipboard unavailable */ }
  };

  const handleOpenInEditor = () => {
    const raw = detectArtifact(`\`\`\`${language}\n${code}\n\`\`\``);
    if (raw) {
      setArtifact(raw);
    } else {
      // Fallback: build artifact manually for short blocks under the detector threshold
      const artifact: Artifact = {
        id: nanoid(),
        type: 'code',
        language: language || 'text',
        content: code,
      };
      setArtifact(artifact);
    }
  };

  return (
    <div className="my-3 overflow-hidden rounded border border-[var(--shadow)]">
      {/* Header bar */}
      <div className="flex items-center justify-between bg-[var(--elevated)] px-3 py-1.5">
        <span className="font-mono text-xs text-[var(--ghost-text)]">
          {language || 'text'}
        </span>
        <div className="flex items-center gap-1">
          <button
            onClick={handleCopy}
            title="Copy code"
            className="rounded p-1 text-[var(--ghost-text)] transition-colors hover:text-[var(--ice-white)]"
          >
            {copied
              ? <Check size={12} className="text-[var(--cyan)]" />
              : <Copy size={12} />}
          </button>
          <button
            onClick={handleOpenInEditor}
            title="Open in editor"
            className="rounded p-1 text-[var(--ghost-text)] transition-colors hover:text-[var(--ice-white)]"
          >
            <ExternalLink size={12} />
          </button>
        </div>
      </div>
      {/* Syntax-highlighted body */}
      <ShikiBlock code={code} language={language || 'text'} />
    </div>
  );
}

// ─── Markdown components override ─────────────────────────────────────────────

function buildComponents(): Components {
  return {
    // Code blocks (fenced) and inline code
    code({ node: _node, className, children, ...props }) {
      const isInline = !className;
      const match = /language-(\w+)/.exec(className ?? '');
      const language = match?.[1] ?? 'text';
      const code = String(children).replace(/\n$/, '');

      return (
        <CodeBlock
          code={code}
          language={language}
          inline={isInline}
          {...(isInline ? props : {})}
        />
      );
    },

    // Ensure <pre> wrapper is transparent (CodeBlock handles its own shell)
    pre({ children }) {
      return <>{children}</>;
    },
  };
}

const markdownComponents = buildComponents();

// ─── MessageProps ─────────────────────────────────────────────────────────────

export interface MessageProps {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: Date | undefined;
}

// ─── Message ──────────────────────────────────────────────────────────────────

export function Message({ role, content, timestamp }: MessageProps) {
  const isUser = role === 'user';

  return (
    <div
      className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'}`}
      role="article"
      aria-label={`${isUser ? 'User' : 'AI'} message`}
    >
      <div
        className={`max-w-[80%] rounded-lg p-4 ${
          isUser
            ? 'border-l-[3px] border-[var(--cyan)] bg-[var(--cyan)]/10 text-[var(--ice-white)]'
            : 'bg-[var(--elevated)]/60 text-[var(--ice-white)]'
        }`}
      >
        {/* Message content */}
        {isUser ? (
          // User messages: plain pre-wrap (no need to parse markdown)
          <p className="m-0 whitespace-pre-wrap break-words text-sm">{content}</p>
        ) : (
          // Assistant messages: full markdown rendering
          <div className="prose prose-invert prose-sm max-w-none">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={markdownComponents}
            >
              {content}
            </ReactMarkdown>
          </div>
        )}

        {/* Timestamp */}
        {timestamp !== undefined && (
          <div className="mt-2 text-xs text-[var(--mist)]">
            {timestamp.toLocaleTimeString('en-US', {
              hour: '2-digit',
              minute: '2-digit',
            })}
          </div>
        )}
      </div>
    </div>
  );
}
