/**
 * Message Component — Sprint 2D update
 *
 * Renders a single message in the strategic thread.
 * Assistant messages: full markdown via react-markdown + remark-gfm.
 * Code blocks: Shiki syntax highlighting + language label + copy + open-in-editor.
 *
 * Design: docs/DESIGN_SYSTEM.md Part 3 (Message Rendering)
 */

'use client';

import { useState, useEffect } from 'react';
import { Copy, Check, ExternalLink } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { Components } from 'react-markdown';
import { nanoid } from 'nanoid';
import { useArtifactStore } from '@/lib/artifacts/store';
import { detectArtifact } from '@/lib/artifacts/detector';
import type { Artifact } from '@/lib/artifacts/types';
import { CollapsibleBlock } from './CollapsibleBlock';

// ─── Shiki singleton ─────────────────────────────────────────────────────────
// Initialised once; subsequent calls return the cached promise.

import type { Highlighter } from 'shiki';

let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  if (!highlighterPromise) {
    highlighterPromise = import('shiki').then(({ createHighlighter }) =>
      createHighlighter({
        themes: ['github-dark'],
        langs: [
          'typescript', 'tsx', 'javascript', 'jsx',
          'python', 'rust', 'go', 'java', 'c', 'cpp',
          'sql', 'json', 'yaml', 'toml', 'bash', 'sh',
          'html', 'css', 'markdown', 'text',
        ],
      }),
    );
  }
  return highlighterPromise;
}

// ─── Shiki code block ────────────────────────────────────────────────────────

interface ShikiBlockProps {
  code: string;
  language: string;
}

function ShikiBlock({ code, language }: ShikiBlockProps) {
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    getHighlighter()
      .then((hl) => {
        // Normalise unknown languages to 'text' so Shiki never throws
        const langs = hl.getLoadedLanguages() as string[];
        const lang = langs.includes(language) ? language : 'text';

        const highlighted = hl.codeToHtml(code, {
          lang,
          theme: 'github-dark',
        });

        if (!cancelled) setHtml(highlighted);
      })
      .catch(() => {
        // Fallback: plain rendering
        if (!cancelled) setHtml(null);
      });

    return () => { cancelled = true; };
  }, [code, language]);

  if (!html) {
    // Plain fallback while Shiki loads (or on error)
    return (
      <pre className="overflow-x-auto rounded-b bg-[#0d1117] p-4 text-xs font-mono text-[var(--ice-white)]">
        <code>{code}</code>
      </pre>
    );
  }

  return (
    <div
      className="overflow-x-auto rounded-b text-xs [&>pre]:!bg-[#0d1117] [&>pre]:p-4 [&>pre]:m-0"
      // Safe: HTML is generated by Shiki from our own code string, never from user input
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

// ─── Inline code block with toolbar ──────────────────────────────────────────

interface CodeBlockProps {
  code: string;
  language: string;
  inline?: boolean;
}

function CodeBlock({ code, language, inline = false }: CodeBlockProps) {
  const [copied, setCopied] = useState(false);
  const { setArtifact } = useArtifactStore();

  if (inline) {
    return (
      <code className="rounded bg-[var(--elevated)] px-1.5 py-0.5 font-mono text-xs text-[var(--cyan)]">
        {code}
      </code>
    );
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch { /* clipboard unavailable */ }
  };

  const handleOpenInEditor = () => {
    const raw = detectArtifact(`\`\`\`${language}\n${code}\n\`\`\``);
    if (raw) {
      setArtifact(raw);
    } else {
      // Fallback: build artifact manually for short blocks under the detector threshold
      const artifact: Artifact = {
        id: nanoid(),
        type: 'code',
        language: language || 'text',
        content: code,
      };
      setArtifact(artifact);
    }
  };

  return (
    <div className="my-3 overflow-hidden rounded border border-[var(--shadow)]">
      {/* Header bar */}
      <div className="flex items-center justify-between bg-[var(--elevated)] px-3 py-1.5">
        <span className="font-mono text-xs text-[var(--ghost-text)]">
          {language || 'text'}
        </span>
        <div className="flex items-center gap-1">
          <button
            onClick={handleCopy}
            title="Copy code"
            className="rounded p-1 text-[var(--ghost-text)] transition-colors hover:text-[var(--ice-white)]"
          >
            {copied
              ? <Check size={12} className="text-[var(--cyan)]" />
              : <Copy size={12} />}
          </button>
          <button
            onClick={handleOpenInEditor}
            title="Open in editor"
            className="rounded p-1 text-[var(--ghost-text)] transition-colors hover:text-[var(--ice-white)]"
          >
            <ExternalLink size={12} />
          </button>
        </div>
      </div>
      {/* Syntax-highlighted body */}
      <ShikiBlock code={code} language={language || 'text'} />
    </div>
  );
}

// ─── Markdown components override ─────────────────────────────────────────────

function buildComponents(): Components {
  return {
    // Code blocks (fenced) and inline code
    code({ node: _node, className, children, ...props }) {
      const isInline = !className;
      const match = /language-(\w+)/.exec(className ?? '');
      const language = match?.[1] ?? 'text';
      const code = String(children).replace(/\n$/, '');

      return (
        <CodeBlock
          code={code}
          language={language}
          inline={isInline}
          {...(isInline ? props : {})}
        />
      );
    },

    // Ensure <pre> wrapper is transparent (CodeBlock handles its own shell)
    pre({ children }) {
      return <>{children}</>;
    },
  };
}

const markdownComponents = buildComponents();

// ─── MessageBlock & MessageProps ────────────────────────────────────────────

export interface MessageBlock {
  type: 'text' | 'thinking' | 'tool_use' | 'tool_result';
  content: string;
  metadata?: Record<string, unknown>;
}

export interface MessageProps {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: Date | undefined;
  /** When set, matching substrings are wrapped in <mark> for search highlight */
  highlightQuery?: string | undefined;
  /** Whether this message is the active search match (for scroll-to) */
  isActiveMatch?: boolean | undefined;
  /** S9-20: Show Edit button on hover (last user message only) */
  onEdit?: (() => void) | undefined;
  /** S9-20: Show Regenerate button on hover (last assistant message only) */
  onRegenerate?: (() => void) | undefined;
  // New streaming fields
  isStreaming?: boolean | undefined;
  model?: string | undefined;
  tokens?: number | undefined;
  costUsd?: number | undefined;
  latencyMs?: number | undefined;
  // Block-based content
  blocks?: MessageBlock[] | undefined;
}

// ─── Highlight helper ─────────────────────────────────────────────────────────

function highlightText(text: string, query: string): React.ReactNode {
  if (!query) return text;
  const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const parts = text.split(new RegExp(`(${escaped})`, 'gi'));
  return parts.map((part, i) =>
    part.toLowerCase() === query.toLowerCase() ? (
      <mark
        key={i}
        style={{
          background: 'var(--amber, #f59e0b)',
          color: 'var(--deep-space, #0d1117)',
          borderRadius: '2px',
          padding: '0 1px',
        }}
      >
        {part}
      </mark>
    ) : (
      part
    ),
  );
}

// ─── Message ──────────────────────────────────────────────────────────────────

export function Message({ role, content, timestamp, highlightQuery, isActiveMatch,
  onEdit, onRegenerate, isStreaming, model, tokens, costUsd, latencyMs, blocks }: MessageProps) {
  const isUser = role === 'user';
  const showActions = onEdit || onRegenerate;

  return (
    <div
      className="group/msg w-full"
      role="article"
      aria-label={`${isUser ? 'User' : 'AI'} message`}
      data-active-match={isActiveMatch ? 'true' : undefined}
      style={{
        padding: 'var(--msg-padding, 8px 0)',
        scrollMarginTop: isActiveMatch ? '80px' : undefined,
      }}
    >
      {/* Role label */}
      <div
        className="mb-1 font-semibold"
        style={{
          fontSize: 'var(--msg-role-size, 11px)',
          color: isUser ? 'var(--cyan)' : 'var(--frost)',
        }}
      >
        {isUser ? 'You' : 'GregLite'}
      </div>

      {/* Content — subtle left border for user messages only */}
      <div
        style={{
          borderLeft: isUser ? '2px solid var(--cyan)' : 'none',
          paddingLeft: isUser ? '12px' : '0',
          fontSize: 'var(--msg-font-size, 14px)',
          lineHeight: 'var(--msg-line-height, 1.5)',
        }}
        className="text-[var(--ice-white)]"
      >
        {isUser ? (
          <p className="m-0 whitespace-pre-wrap break-words">
            {highlightQuery ? highlightText(content, highlightQuery) : content}
          </p>
        ) : blocks && blocks.length > 0 ? (
          /* Block-based rendering (structured content from SSE) */
          <div className="prose prose-invert max-w-none" style={{ fontSize: 'inherit', lineHeight: 'inherit' }}>
            {blocks.map((block, i) => {
              if (block.type === 'text') {
                return (
                  <ReactMarkdown key={i} remarkPlugins={[remarkGfm]} components={markdownComponents}>
                    {block.content}
                  </ReactMarkdown>
                );
              }
              if (block.type === 'thinking') {
                const duration = block.metadata?.duration_ms
                  ? `${Math.round((block.metadata.duration_ms as number) / 1000)}s`
                  : '';
                return (
                  <CollapsibleBlock key={i} type="thinking" summary={`Thought${duration ? ` for ${duration}` : ''}`}>
                    <p className="whitespace-pre-wrap text-[var(--mist)]">{block.content}</p>
                  </CollapsibleBlock>
                );
              }
              if (block.type === 'tool_use') {
                const toolName = (block.metadata?.name as string) ?? 'tool';
                return (
                  <CollapsibleBlock key={i} type="tool_use" summary={`Used ${toolName}`}>
                    <pre className="text-[11px] font-mono whitespace-pre-wrap text-[var(--frost)]">
                      {block.content}
                    </pre>
                  </CollapsibleBlock>
                );
              }
              return null;
            })}
          </div>
        ) : !isUser ? (
          /* Fallback: single content string (backwards compatible) */
          <div className="prose prose-invert max-w-none" style={{ fontSize: 'inherit', lineHeight: 'inherit' }}>
            {highlightQuery ? (
              <p className="m-0 whitespace-pre-wrap break-words">
                {highlightText(content, highlightQuery)}
              </p>
            ) : (
              <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                {content}
              </ReactMarkdown>
            )}
          </div>
        ) : null}

        {/* Streaming cursor */}
        {isStreaming && (
          <span className="inline-block animate-pulse text-[var(--cyan)]">▌</span>
        )}
      </div>

      {/* Edit / Regenerate hover actions */}
      {showActions && (
        <div className="mt-1 flex items-center gap-2 opacity-0 group-hover/msg:opacity-100 transition-opacity">
          {onEdit && (
            <button onClick={onEdit}
              className="flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-medium text-[var(--mist)] hover:text-[var(--ice-white)] hover:bg-[var(--surface)] transition-colors"
              title="Edit message (Cmd+E)">✎ Edit</button>
          )}
          {onRegenerate && (
            <button onClick={onRegenerate}
              className="flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-medium text-[var(--mist)] hover:text-[var(--ice-white)] hover:bg-[var(--surface)] transition-colors"
              title="Regenerate (Cmd+R)">↻ Regenerate</button>
          )}
        </div>
      )}

      {/* Timestamp + metadata */}
      <div className="mt-1 flex items-center gap-2 text-[10px] text-[var(--mist)]">
        {timestamp !== undefined && (
          <span>{timestamp.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</span>
        )}
        {!isStreaming && model && (
          <>
            <span>·</span>
            <span>{model.replace('claude-', '').split('-')[0]}</span>
          </>
        )}
        {!isStreaming && tokens !== undefined && tokens > 0 && (
          <>
            <span>·</span>
            <span>{tokens.toLocaleString()} tokens</span>
          </>
        )}
        {!isStreaming && costUsd !== undefined && costUsd > 0 && (
          <>
            <span>·</span>
            <span>${costUsd.toFixed(4)}</span>
          </>
        )}
        {!isStreaming && latencyMs !== undefined && latencyMs > 0 && (
          <>
            <span>·</span>
            <span>{(latencyMs / 1000).toFixed(1)}s</span>
          </>
        )}
      </div>
    </div>
  );
}
