/**
 * Ghost Scorer — Type Definitions
 *
 * GhostCandidate   — enriched chunk from vec_index (post-retrieval, pre-scoring)
 * GhostSuggestion  — scored candidate that has passed the window check and been surfaced
 * ScorerConfig     — runtime configuration for the interrupt scoring engine
 */

// ─── Candidate (retrieved from vec_index, before scoring) ────────────────────

export interface GhostCandidate {
  chunkId: string;
  text: string;
  similarity: number;
  sourcePath: string | null;
  sourceType: string;
  sourceAccount: string | null;
  indexedAt: number;
  isCritical: boolean;
  /** Raw parsed metadata from content_chunks.metadata */
  metadata: Record<string, unknown> | null;
}

// ─── Suggestion (surfaced to the context panel) ───────────────────────────────

export interface GhostSuggestion {
  id: string;
  chunkId: string;
  score: number;
  similarity: number;
  /** One-sentence summary generated by Claude Haiku */
  summary: string;
  /** 'File: /path/to/file.md' or 'Email: Subject Line' */
  source: string;
  sourcePath: string;
  surfacedAt: number;
  /** surfacedAt + 4 hours — auto-expire */
  expiresAt: number;
  isCritical: boolean;
}

// ─── Scorer configuration ─────────────────────────────────────────────────────

export interface ScorerConfig {
  /** Minimum similarity score to be considered a candidate (default 0.75) */
  minSimilarity: number;
  /** Number of Ghost chunks to retrieve from vec_index (default 50) */
  candidateK: number;
  /** Scheduler interval in ms (default 6h) */
  intervalMs: number;
  /** Maximum suggestions surfaced per rolling window (default 2) */
  maxPerWindow: number;
  /** Rolling window length in ms (default 24h) */
  windowMs: number;
  /** Suggestion auto-expiry in ms (default 4h) */
  suggestionTtlMs: number;
}

export const DEFAULT_SCORER_CONFIG: ScorerConfig = {
  minSimilarity: 0.75,
  candidateK: 50,
  intervalMs: 6 * 60 * 60 * 1000,       // 6 hours
  maxPerWindow: 2,
  windowMs: 24 * 60 * 60 * 1000,         // 24 hours
  suggestionTtlMs: 4 * 60 * 60 * 1000,   // 4 hours
};
