/**
 * Portfolio Scaffold — Sprint 26.0
 *
 * Scaffold templates for each project type. Creates a full directory of
 * tracking files from onboarding answers. Registers the new project in SQLite.
 *
 * Public API:
 *   getScaffoldTemplate(type)                      — returns the template for a type
 *   scaffoldProject(template, dirPath, answers)    — creates directory + files
 *   registerProject(dirPath, name, type, label?)   — INSERT into portfolio_projects
 *   substituteAnswers(content, answers)            — {{variable}} substitution helper
 *
 * RULE: All file paths are relative within the new project directory.
 * RULE: No LLM calls here — templates are deterministic from answers.
 */

import fs from 'fs';
import path from 'path';
import { stringify as stringifyYaml } from 'yaml';
import { getDatabase } from '@/lib/kernl/database';
import { scanSingleProject } from './scanner';
import type {
  ProjectType,
  ScaffoldTemplate,
  ScaffoldResult,
} from './types';

// ── Substitution helper ───────────────────────────────────────────────────────

/**
 * Replace {{key}} placeholders in a string with values from answers.
 * Unknown keys are replaced with an empty string.
 */
export function substituteAnswers(
  content: string,
  answers: Record<string, string>,
): string {
  return content.replace(/\{\{(\w+)\}\}/g, (_, key: string) => answers[key] ?? '');
}

// ── Date helper ───────────────────────────────────────────────────────────────

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// ── Code template ─────────────────────────────────────────────────────────────

const CODE_TEMPLATE: ScaffoldTemplate = {
  type: 'code',
  label: 'Code',
  files: [
    {
      path: 'PROJECT_DNA.yaml',
      content: (a) => `# PROJECT_DNA.yaml\n# Generated by GregLite — ${today()}\n\n${stringifyYaml({
        identity: { name: a['name'] ?? 'Unnamed Project', purpose: a['purpose'] ?? a['description'] ?? '' },
        type: 'code',
        current_state: {
          version: 'v0.1.0',
          phase: 'Phase 1 — Foundation',
          status: 'Active development.',
        },
        metrics: {
          language: a['language'] ?? null,
          platform: a['platform'] ?? null,
          team: a['team'] ?? 'solo',
          test_count: 0,
          tsc_errors: 'N/A',
          last_commit: null,
        },
        documents: ['PROJECT_DNA.yaml', 'STATUS.md', 'FEATURE_BACKLOG.md', 'README.md'],
      })}`,
    },
    {
      path: 'STATUS.md',
      content: (a) => [
        `# STATUS.md`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `**Last Updated:** ${today()} — Project created.`,
        `**Version:** v0.1.0`,
        `**Test Count:** 0/0 all green`,
        `**TSC:** N/A`,
        `**Next:** Sprint 1 TBD`,
        ``,
        `---`,
        ``,
        `- [ ] **SPRINT 1.0** — Initial setup — **IN PROGRESS**`,
        `  - Define project structure`,
        `  - Set up build system`,
        `  - Write first tests`,
        ``,
      ].join('\n'),
    },
    {
      path: 'FEATURE_BACKLOG.md',
      content: (a) => [
        `# FEATURE BACKLOG`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `# Created: ${today()}`,
        ``,
        `## Status Key`,
        `- SHIPPED — Complete and merged`,
        `- NEXT — Planned for upcoming sprint`,
        `- MISSING — Identified gap, not scheduled`,
        ``,
        `## Priority 1 — Core`,
        ``,
        `## Priority 2 — Enhancements`,
        ``,
        `## Backlog`,
        ``,
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: (a) => [
        `# ${a['name'] ?? 'Unnamed Project'}`,
        ``,
        `${a['purpose'] ?? a['description'] ?? ''}`,
        ``,
        `## Getting Started`,
        ``,
        `${a['language'] ? `Language/framework: ${a['language']}` : ''}`,
        `${a['platform'] ? `Platform: ${a['platform']}` : ''}`,
        ``,
        `## Development`,
        ``,
        `TBD`,
        ``,
      ].join('\n'),
    },
  ],
};

// ── Research template ─────────────────────────────────────────────────────────

const RESEARCH_TEMPLATE: ScaffoldTemplate = {
  type: 'research',
  label: 'Research',
  files: [
    {
      path: 'PROJECT_DNA.yaml',
      content: (a) => `# PROJECT_DNA.yaml\n# Generated by GregLite — ${today()}\n\n${stringifyYaml({
        identity: { name: a['name'] ?? 'Unnamed Research', purpose: a['research_question'] ?? a['purpose'] ?? '' },
        type: 'research',
        current_state: {
          phase: 'Phase 1 — Literature Review',
          status: 'Active research.',
        },
        metrics: {
          research_question: a['research_question'] ?? null,
          methodology: a['methodology'] ?? null,
          timeline: a['timeline'] ?? null,
          document_count: 0,
        },
        documents: ['PROJECT_DNA.yaml', 'STATUS.md', 'RESEARCH_LOG.md', 'METHODOLOGY.md', 'README.md'],
      })}`,
    },
    {
      path: 'STATUS.md',
      content: (a) => [
        `# STATUS.md`,
        `# ${a['name'] ?? 'Unnamed Research'}`,
        `**Last Updated:** ${today()} — Project created.`,
        `**Phase:** Phase 1 — Literature Review`,
        `**Documents:** 0`,
        `**Next:** Define scope and begin literature search`,
        ``,
        `---`,
        ``,
        `## Current Phase`,
        `Phase 1 — Literature Review`,
        ``,
        `## Recent Findings`,
        ``,
        `## Next Steps`,
        ``,
      ].join('\n'),
    },
    {
      path: 'RESEARCH_LOG.md',
      content: (a) => [
        `# RESEARCH LOG`,
        `# ${a['name'] ?? 'Unnamed Research'}`,
        `# Created: ${today()}`,
        ``,
        `Format: ## YYYY-MM-DD — Finding or milestone`,
        ``,
        `---`,
        ``,
        `## ${today()} — Project initialized`,
        ``,
        `Research question: ${a['research_question'] ?? 'TBD'}`,
        ``,
      ].join('\n'),
    },
    {
      path: 'METHODOLOGY.md',
      content: (a) => [
        `# METHODOLOGY`,
        `# ${a['name'] ?? 'Unnamed Research'}`,
        `# Created: ${today()}`,
        ``,
        `## Research Question`,
        `${a['research_question'] ?? 'TBD'}`,
        ``,
        `## Methodology`,
        `${a['methodology'] ?? 'TBD'}`,
        ``,
        `## Data Sources`,
        ``,
        `## Analysis Approach`,
        ``,
        `## Expected Outputs`,
        `${a['outputs'] ?? 'TBD'}`,
        ``,
        `## Timeline`,
        `${a['timeline'] ?? 'TBD'}`,
        ``,
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: (a) => [
        `# ${a['name'] ?? 'Unnamed Research'}`,
        ``,
        `**Research Question:** ${a['research_question'] ?? 'TBD'}`,
        ``,
        `**Methodology:** ${a['methodology'] ?? 'TBD'}`,
        ``,
        `**Timeline:** ${a['timeline'] ?? 'TBD'}`,
        ``,
      ].join('\n'),
    },
  ],
};

// ── Business template ─────────────────────────────────────────────────────────

const BUSINESS_TEMPLATE: ScaffoldTemplate = {
  type: 'business',
  label: 'Business',
  files: [
    {
      path: 'PROJECT_DNA.yaml',
      content: (a) => `# PROJECT_DNA.yaml\n# Generated by GregLite — ${today()}\n\n${stringifyYaml({
        identity: { name: a['name'] ?? 'Unnamed Project', purpose: a['deliverable'] ?? a['purpose'] ?? '' },
        type: 'business',
        current_state: {
          phase: 'Phase 1 — Initiation',
          status: 'Active.',
        },
        metrics: {
          deliverable: a['deliverable'] ?? null,
          client: a['client'] ?? null,
          milestones: a['milestones'] ?? null,
          success_kpi: a['success_kpi'] ?? null,
          next_deliverable: null,
        },
        documents: ['PROJECT_DNA.yaml', 'STATUS.md', 'MILESTONES.md', 'README.md'],
      })}`,
    },
    {
      path: 'STATUS.md',
      content: (a) => [
        `# STATUS.md`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `**Last Updated:** ${today()} — Project created.`,
        `**Phase:** Phase 1 — Initiation`,
        `**Client:** ${a['client'] ?? 'TBD'}`,
        `**Next Deliverable:** ${a['deliverable'] ?? 'TBD'}`,
        ``,
        `---`,
        ``,
        `## Current Phase`,
        `Phase 1 — Initiation`,
        ``,
        `## Active Work`,
        ``,
        `## Upcoming Milestones`,
        ``,
      ].join('\n'),
    },
    {
      path: 'MILESTONES.md',
      content: (a) => [
        `# MILESTONES`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `# Created: ${today()}`,
        ``,
        `## Status Key`,
        `- [ ] Not started`,
        `- [~] In progress`,
        `- [x] Complete`,
        ``,
        `---`,
        ``,
        `## Phase 1 — Initiation`,
        `- [ ] Define scope`,
        `- [ ] ${a['deliverable'] ? `Deliver: ${a['deliverable']}` : 'First deliverable TBD'}`,
        ``,
        `## Phase 2 — Execution`,
        ``,
        `## Phase 3 — Completion`,
        ``,
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: (a) => [
        `# ${a['name'] ?? 'Unnamed Project'}`,
        ``,
        `**Client:** ${a['client'] ?? 'TBD'}`,
        `**Deliverable:** ${a['deliverable'] ?? 'TBD'}`,
        `**Success KPI:** ${a['success_kpi'] ?? 'TBD'}`,
        ``,
        `## Milestones`,
        `${a['milestones'] ?? 'See MILESTONES.md'}`,
        ``,
      ].join('\n'),
    },
  ],
};

// ── Creative template ─────────────────────────────────────────────────────────

const CREATIVE_TEMPLATE: ScaffoldTemplate = {
  type: 'creative',
  label: 'Creative',
  files: [
    {
      path: 'PROJECT_DNA.yaml',
      content: (a) => `# PROJECT_DNA.yaml\n# Generated by GregLite — ${today()}\n\n${stringifyYaml({
        identity: { name: a['name'] ?? 'Unnamed Project', purpose: a['purpose'] ?? a['description'] ?? '' },
        type: 'creative',
        current_state: {
          phase: 'Phase 1 — In Progress',
          status: 'Active.',
        },
        metrics: {
          medium: a['medium'] ?? null,
          audience: a['audience'] ?? null,
          scope: a['scope'] ?? null,
          progress: '0%',
          target_completion: a['target_completion'] ?? null,
        },
        documents: ['PROJECT_DNA.yaml', 'STATUS.md', 'TASK_LIST.md', 'README.md'],
      })}`,
    },
    {
      path: 'STATUS.md',
      content: (a) => [
        `# STATUS.md`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `**Last Updated:** ${today()} — Project created.`,
        `**Phase:** Phase 1 — In Progress`,
        `**Progress:** 0%`,
        `**Next:** ${a['scope'] ?? 'First task TBD'}`,
        ``,
        `---`,
        ``,
        `## Current Phase`,
        `Phase 1 — In Progress`,
        ``,
        `## Recent Progress`,
        ``,
        `## Next Steps`,
        ``,
      ].join('\n'),
    },
    {
      path: 'TASK_LIST.md',
      content: (a) => [
        `# TASK LIST`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `# Created: ${today()}`,
        ``,
        `Medium: ${a['medium'] ?? 'TBD'}`,
        `Audience: ${a['audience'] ?? 'TBD'}`,
        ``,
        `---`,
        ``,
        `## Active`,
        `- [ ] Initial setup`,
        ``,
        `## Upcoming`,
        ``,
        `## Done`,
        ``,
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: (a) => [
        `# ${a['name'] ?? 'Unnamed Project'}`,
        ``,
        `**Medium:** ${a['medium'] ?? 'TBD'}`,
        `**Audience:** ${a['audience'] ?? 'TBD'}`,
        `**Scope:** ${a['scope'] ?? 'TBD'}`,
        ``,
      ].join('\n'),
    },
  ],
};

// ── Custom template ───────────────────────────────────────────────────────────

const CUSTOM_TEMPLATE: ScaffoldTemplate = {
  type: 'custom',
  label: 'Custom',
  files: [
    {
      path: 'PROJECT_DNA.yaml',
      content: (a) => `# PROJECT_DNA.yaml\n# Generated by GregLite — ${today()}\n\n${stringifyYaml({
        identity: { name: a['name'] ?? 'Unnamed Project', purpose: a['purpose'] ?? '' },
        type: 'custom',
        type_label: a['type_label'] ?? 'Custom',
        current_state: {
          phase: 'Phase 1 — In Progress',
          status: 'Active.',
        },
        metrics: {
          inputs: a['inputs'] ?? null,
          done_looks_like: a['done_looks'] ?? null,
          constraints: a['constraints'] ?? null,
          success_signal: a['success_signal'] ?? null,
        },
        documents: ['PROJECT_DNA.yaml', 'STATUS.md', 'TASK_LIST.md', 'README.md'],
      })}`,
    },
    {
      path: 'STATUS.md',
      content: (a) => [
        `# STATUS.md`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `**Last Updated:** ${today()} — Project created.`,
        `**Phase:** Phase 1 — In Progress`,
        `**Next:** TBD`,
        ``,
        `---`,
        ``,
        `## Current Phase`,
        `Phase 1 — In Progress`,
        ``,
        `## Status`,
        ``,
        `## Next`,
        ``,
      ].join('\n'),
    },
    {
      path: 'TASK_LIST.md',
      content: (a) => [
        `# TASK LIST`,
        `# ${a['name'] ?? 'Unnamed Project'}`,
        `# Created: ${today()}`,
        ``,
        `Purpose: ${a['purpose'] ?? 'TBD'}`,
        ``,
        `---`,
        ``,
        `## Active`,
        `- [ ] Initial setup`,
        ``,
        `## Upcoming`,
        ``,
        `## Done`,
        ``,
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: (a) => [
        `# ${a['name'] ?? 'Unnamed Project'}`,
        ``,
        `${a['purpose'] ?? ''}`,
        ``,
        `**Inputs:** ${a['inputs'] ?? 'TBD'}`,
        `**Done looks like:** ${a['done_looks'] ?? 'TBD'}`,
        `**Success signal:** ${a['success_signal'] ?? 'TBD'}`,
        ``,
      ].join('\n'),
    },
  ],
};

// ── Template registry ─────────────────────────────────────────────────────────

const TEMPLATES: Record<ProjectType, ScaffoldTemplate> = {
  code:     CODE_TEMPLATE,
  research: RESEARCH_TEMPLATE,
  business: BUSINESS_TEMPLATE,
  creative: CREATIVE_TEMPLATE,
  custom:   CUSTOM_TEMPLATE,
};

export function getScaffoldTemplate(type: ProjectType): ScaffoldTemplate {
  const template = TEMPLATES[type];
  if (!template) {
    throw new Error(`No scaffold template found for type: "${String(type)}"`);
  }
  return template;
}

// ── Scaffold execution ────────────────────────────────────────────────────────

/**
 * Create the project directory and write all template files.
 * answer substitution is applied to all content functions and strings.
 */
export function scaffoldProject(
  template: ScaffoldTemplate,
  dirPath: string,
  answers: Record<string, string>,
): ScaffoldResult {
  const filesCreated: string[] = [];

  try {
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  } catch (err) {
    return {
      success: false,
      filesCreated: [],
      error: `Failed to create directory: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  for (const file of template.files) {
    try {
      const rawContent = typeof file.content === 'function'
        ? file.content(answers)
        : substituteAnswers(file.content, answers);

      const filePath = path.join(dirPath, file.path);

      // Create parent directories if needed (e.g. nested files)
      const parentDir = path.dirname(filePath);
      if (!fs.existsSync(parentDir)) {
        fs.mkdirSync(parentDir, { recursive: true });
      }

      // Never overwrite an existing file (safe — user may have created files already)
      if (!fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, rawContent, 'utf8');
        filesCreated.push(file.path);
      }
    } catch (err) {
      console.warn(`[portfolio/scaffold] Failed to write ${file.path}:`, err);
    }
  }

  return { success: true, filesCreated };
}

// ── Project registration ──────────────────────────────────────────────────────

/**
 * INSERT the new project into portfolio_projects and trigger an immediate scan.
 */
export function registerProject(
  dirPath: string,
  name: string,
  type: ProjectType,
  typeLabel?: string,
): string {
  const db = getDatabase();
  const id = `proj_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const now = Date.now();

  db.prepare(`
    INSERT OR IGNORE INTO portfolio_projects
      (id, name, path, type, type_label, status, registered_at)
    VALUES (?, ?, ?, ?, ?, 'active', ?)
  `).run(id, name.trim(), dirPath, type, typeLabel ?? null, now);

  // Trigger immediate scan (non-blocking)
  void Promise.resolve().then(() => {
    try {
      scanSingleProject(dirPath);
    } catch (err) {
      console.warn('[portfolio/scaffold] Post-registration scan failed:', err);
    }
  });

  return id;
}
